#!/bin/bash

# rc.bash
# jessy@jessywilliams.com

# ------------------------------------------------------------------------------

# if not running interactively, don't do anything else
[[ $- != *i* ]] && return
source ~/.profile

# only load once per session

# bash completions
bash_completion_path='/usr/share/bash-completion/bash_completion'
[ -f "$bash_completion_path" ] && source "$bash_completion_path"

# history
shopt -s histappend

# More lenient text expansion and globbing
shopt -s cdspell
shopt -s expand_aliases
shopt -s hostcomplete
shopt -s nocaseglob
shopt -s nocasematch

# source shell scripts
if [ -d "$HOME/.config/tty" ]; then
    for file in "$HOME"/.config/tty/*.{sh,bash}; do
        source "$file"
    done
    unset file
fi

# mise
command -v mise >/dev/null 2>&1 && eval "$(mise activate bash)"

# fzf
[ -r "$HOME/.fzf.bash" ] && source "$HOME/.fzf.bash"

[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"
