[tools]
bun = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
gum = "latest"
node = "26"
python = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true

[env]
_.file = "~/.env"

